### ISSUE TITLE
Preference Pairing

### ISSUE THREAD

**Issue by twidatalla** [Harmonic-Discovery/pref-opt-for-mols#1]
Hello, 

I noticed when creating your positive negative pairs you guys did:

```
            # Generate positive-negative pairs
            pos = self._data[self._data[self.label_key]]
            neg = self._data[~self._data[self.label_key]]

            # Sample positive-negative pairs
            pos_smiles = pos[self.smiles_key].sample(n, replace=True)
            neg_smiles = neg[self.smiles_key].sample(n, replace=True)

            self.smiles_pairs = np.stack([pos_smiles, neg_smiles], axis=1)
            self.smiles_pairs = np.stack([pos_smiles, neg_smiles], axis=1)
```

Correct me if I'm wrong (since I only skimmed the code) but it seems like you guys randomly sampled n positive and n negative pairs, and assigned a single pair between the positive and negative samples. Does this pair mapping change every epoch? Or is there a fixed pairing throughout all of training? Also did you guys ever consider doing multiple pairs (since theres theoretically n^2 pairings you can do if both datasets are length n)

**Comment by ryspark** [comment]
Thanks for the question! Yes, we assign a fixed single positive-negative pairing, this doesn't change throughout training. Since the dataset used for DPO fine-tuning is sampled from a base model, it can be as large as you want (in the paper we sampled 100K I believe). For that reason, generating all n^2 pairings wasn't necessary, it's easy to synthetically scale up the size of the dataset if need be.
